### ISSUE TITLE
Perms

### ISSUE THREAD

**Issue by Mindmaster456** [BlackBeltPanda/TwerkFarm#1]
None of my players can use this plugin and I'm not sure how to fix. please help!

**Comment by BlackBeltPanda** [comment]
What permissions did you give your players?

**Comment by Mindmaster456** [comment]
I didn't give any perms, I thought it did it itself. How would I give the perms?

**Comment by BlackBeltPanda** [comment]
Give the players the permission, `twerfarm.twerk.<material_name>` if you want them to only be able to twerk for specific materials. Otherwise, if you want them to be able to twerk for all whitelisted materials, give them the permission, `twerkfarm.twerk.*`.
