### ISSUE TITLE
only admins can use it

### ISSUE THREAD

**Issue by jackyboy1992** [BlackBeltPanda/TwerkFarm#2]
so only the admins on the server can use the plugin ive tried using this command twerkfarm.twerk.* but it doesnt work just shows red then says if i need help to do /help 
![image_2022-01-14_121124](https://user-images.githubusercontent.com/1923334/149513587-9c9bbb4b-da09-4fda-b19f-93d04af0be4a.png)

**Comment by BlackBeltPanda** [comment]
You need to give your players the permission `twerkfarm.twerk.<material_name>` so they can twerk for specific materials or `twerkfarm.twerk.*` if you want them to be able to twerk for all whitelisted materials.
Material names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by jackyboy1992** [comment]
ive tried that but the second command doesnt work /twerkfarm.twerk.* does nothing

**Comment by BlackBeltPanda** [comment]
It's not a command, it's a permission node. You need to add that permission with your permission plugin.
More info on permissions: https://bukkit.fandom.com/wiki/Understanding_Permissions

**Comment by jackyboy1992** [comment]
so ive got luckyperms on the server would i have to use that to allow others to use twerk farm?

**Comment by BlackBeltPanda** [comment]
Yes, with luckperms the command would be `/lp group <group> permission set <permission>`.
For example, if you want all players to be able to twerk for all materials, you'd use `/lp group default permission set twerkfarm.twerk.*`.

**Comment by jackyboy1992** [comment]
perfect thats worked a treat thanks very much for the help

**Comment by BlackBeltPanda** [comment]
You're welcome. =)
Closing as issue resolved.
